# GLOBAL SITE SETTINGS

# General
seo_title: ""
title: ""
company: "Liquid Visual"
description: ""

# Contact Info
email: hello@liquidvisual.com
phone: (05) 555 555
fax: (05) 555 555
address: "ABC Street, Earth"

# Social Networks
facebook: ""

# Google Map
google_map: ""

# Google Analytics
google_analytics: "UA-XXXXXXXX-X"